# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobblekarma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma_for', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('karma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gobblekarma.Karma')),
            ],
        ),
    ]
